const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const AggregationPractice = new Schema({

    _id: mongoose.Schema.Types.ObjectId, // Automatically generated by MongoDB
    name: {
        type: String,
        required: true // This field is required
    },
    age: {
        type: Number,
        required: true
    },
    city: {
        type: String,
        required: true
    },
    hobbies: [{
        type: String,
        required: true
    }]
});

module.exports = mongoose.model('AggregationPractice', AggregationPractice)
